print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/cgodden18/Desktop/VRApocalypse-master/VRApocalypse/FarmApocalypse/Assets/Textures/zjjuztywmvb4-well/well/Models/well2.mb"`)
{		
	file -o "/Users/cgodden18/Desktop/VRApocalypse-master/VRApocalypse/FarmApocalypse/Assets/Textures/zjjuztywmvb4-well/well/Models/well2.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/cgodden18/Desktop/VRApocalypse-master/VRApocalypse/FarmApocalypse/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/cgodden18/Desktop/VRApocalypse-master/VRApocalypse/FarmApocalypse/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/cgodden18/Desktop/VRApocalypse-master/VRApocalypse/FarmApocalypse/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
