print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/abeedebor16/Desktop/VRApocalypse/FarmApocalypseRedo/Assets/SceneAssets/Cams scene assets and whatnot/well/Models/well2.mb"`)
{		
	file -o "/Users/abeedebor16/Desktop/VRApocalypse/FarmApocalypseRedo/Assets/SceneAssets/Cams scene assets and whatnot/well/Models/well2.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/abeedebor16/Desktop/VRApocalypse/FarmApocalypseRedo/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/abeedebor16/Desktop/VRApocalypse/FarmApocalypseRedo/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/abeedebor16/Desktop/VRApocalypse/FarmApocalypseRedo/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
